### ISSUE TITLE
PhantomBot requires an input console when starting

### ISSUE THREAD

**Issue by Lyude** [GloriousEggroll/PhantomBot#1]
So, I've been working with Triscy on getting PhantomBot working on their system. The only problem is that it looks like PhantomBot requires that there be some sort of input console to type commands when it's running. This becomes a problem if you're trying to have it run like a normal linux daemon by running it through systemd, so that systemd can monitor/restart the bot as needed and start it up properly on boot. systemd units don't have a stdin by default, so as a result PhantomBot gets angry and starts spamming the log with this:

```
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: Mar 08, 2015 4:43:42 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: SEVERE: Could not dispatch event: me.mast3rplan.phantombot.PhantomBot@77e77a to public void me.mast3rplan.phantombot.PhantomBot.onConsoleMessage(me.mast3rplan.phantombot.event.console.ConsoleInputEvent)
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: Mar 08, 2015 4:43:42 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: SEVERE: Could not dispatch event: me.mast3rplan.phantombot.PhantomBot@77e77a to public void me.mast3rplan.phantombot.PhantomBot.onConsoleMessage(me.mast3rplan.phantombot.event.console.ConsoleInputEvent)
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: Mar 08, 2015 4:43:42 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
Mar 08 17:43:42 TriscyBeardBot launch.sh[1590]: SEVERE: Could not dispatch event: me.mast3rplan.phantombot.PhantomBot@77e77a to public void me.mast3rplan.phantombot.PhantomBot.onConsoleMessage(me.mast3rplan.phantombot.event.console.ConsoleInputEvent)
```

**Comment by GloriousEggroll** [comment]
heya, this is because phantombot's launch.sh uses launch option -Dinteractive, if you remove this from the launch command you can use it as a service :)

**Comment by GloriousEggroll** [comment]
also not that it does try to create a pid when run as a service, so you should either run it as sudo or make sure the user executing it has access to /var/run

**Comment by Lyude** [comment]
Whoops! A little while after making this issue I noticed that in the script. By the way, it should be noted you don't always need a /var/run file, specifically when you're using systemd since it can just track the PID on it's own ;). Anyway, I'll close this issue, sorry for the misunderstanding!

**Comment by GloriousEggroll** [comment]
yeah the reason we made it generate a pid file is because if we dont, it just names the pid file as java rather than as the bot's name. this can be rather bothersome when trying to kill a pre-existing process off if you have other java apps running

**Comment by gmt2001** [comment]
There was an associated service script and service script installer for init.d/chkconfig that went with this and used that PID file but i diddnt include it in the repo
