### ISSUE TITLE
[Command Request] !mutefolloweralert and !mutesubalert

### ISSUE THREAD

**Issue by Ollee** [GloriousEggroll/PhantomBot#12]
Command that toggles a mute for the follower/subscriber chat alerts.

When someone gets a follower or sub run, a command to toggle mute of these alerts until a mod/channel owner issues the command again to turn them on.

Or a !mutefolloweralert <time> that mutes it for some X minutes in <time>

< 3
Ollee

**Comment by GloriousEggroll** [comment]
...
!module disable ./handlers/followHandler.js
!module disable ./handlers/subscribeHandler.js
!module disable ./handlers/hostHandler.js

**Comment by Ollee** [comment]
Thank you very much. Keep up the good work.
