### ISSUE TITLE
Posts now playing twich

### ISSUE THREAD

**Issue by LawlyPopz** [GloriousEggroll/PhantomBot#125]
[♫] Now Playing Song ~ 501 - Falling Skies ~ Requested by @ DJ CandyLandzz
[♫] Now Playing Song ~ 501 - Falling Skies requested by: DJ CandyLandzz ~ Requested by @$2

**Comment by scania123** [comment]
I'm pretty sure this issue has been fixed whit 1.6.5.1

**Comment by phantomindex** [comment]
happens sometimes when you have the player open and you restart the bot while it's still open.

**Comment by gmt2001** [comment]
Already resolved in 717ba4e68e41511380d5873c59e0e9cd5a2c3b35
