### ISSUE TITLE
Phantombot not escaping characters on !Kill command

### ISSUE THREAD

**Issue by Destidom** [GloriousEggroll/PhantomBot#14]
UserName: message deleted
Botlandbot: UserName-> dont spam symbols! 
Symbol limit: 16. Total symbols: 36 [Purged]

Botlandbot: UserName attacked ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ with a rusty spoon 

Even though it purges it repeats what you say when attack message comes up.

**Comment by gmt2001** [comment]
Thats because the bot moderating the user does not stop other scripts from processing the command. This is the current known and intended behavior. There is no bug here
