### ISSUE TITLE
"!quote date" using incorrect enable/disable syntax

### ISSUE THREAD

**Issue by sekkuar** [GloriousEggroll/PhantomBot#220]
When you try to enable or disable the date under the !quote script, it will give a syntax error even though the syntax is correct

![quote date](https://cloud.githubusercontent.com/assets/16503688/12066937/baf88fa8-afd7-11e5-9c5b-c5f889c39e2d.PNG)

**Comment by sekkuar** [comment]
I found the problem!
https://github.com/GloriousEggroll/PhantomBot/blob/master/res/scripts/commands/quoteCommand.js

@line 164

    } else if (args[1] != "enabled" && args[1] != "disabled") {

"enable**d**" and "disable**d**" should be "enable" and "disable" instead

**Comment by sekkuar** [comment]
Also, line 176 uses the wrong string

    $.say($.getWhisperString(sender) + $.lang.get("net.phantombot.quotecommand.-success-disable"));

should be

    $.say($.getWhisperString(sender) + $.lang.get("net.phantombot.quotecommand.date-success-disable"));

![date disabled](https://cloud.githubusercontent.com/assets/16503688/12067720/ff40f00c-afe5-11e5-9e2f-9ce571419a9f.PNG)

**Comment by kojitsari** [comment]
Fixed, can be closed. https://github.com/GloriousEggroll/PhantomBot/pull/225

**Comment by sekkuar** [comment]
Tested and working fine. Thanks!
