### ISSUE TITLE
!game and !title for mods

### ISSUE THREAD

**Issue by EvilTaiga** [GloriousEggroll/PhantomBot#6]
How can my mods use the commands? I have it try with !percom but the bot say "The command !game does not exist!", how can I fix it so the mods can edit the game or title?

**Comment by GloriousEggroll** [comment]
in commands/streamcommands.js line 273+274
$.registerChatCommand("./commands/streamCommands.js", "game", "caster");
$.registerChatCommand("./commands/streamCommands.js", "title", "caster");
change caster to mod
