### ISSUE TITLE
Message rate limiting by connection instead of by channel

### ISSUE THREAD

**Issue by gmt2001** [GloriousEggroll/PhantomBot#67]
Message rate limiting is currently implemented at the Channel level when it should be implemented at the Session level.

Easiest way to do it would be to do a Session level nextMessageSendTime method, with a random delay up to 20ms added by the Channel to give other Channel's a chance.

A mutex will also be needed to prevent multiple channels from accidentally getting the okay

**Comment by Ollee** [comment]
Why not do a session level queue where each channel issues a send request
to the queue and the bot can then keep track of how fast it is sending
messages and throttle if it is going too fast?

-Christopher Wilhelm

**Comment by scania123** [comment]
Just wanted to let you know that the message rate limit has been changed on twitch to 100msg in 30seconds for moderators+ but I'm not sure if it is still like that. https://discuss.dev.twitch.tv/t/message-limit-for-moderators/3042/3

**Comment by gmt2001** [comment]
I may actually do that, what I wrote was just the easier one because the loop that processes the queue was already built-in to Channel (even before I added the rate limit and priority queue). I have known about the 100 rate limit  forever. I set the bots default to 18.75 (dont remember if phamtom/glori changed it) as a safety feature in case the bot was being tested in a channel and got demodded

**Comment by Ollee** [comment]
It'd probably be wise to build in a "isMod" check for each channel and then
handle the rate limit accordingly, since whoever tackles this will be in
that code anyways.

-Christopher Wilhelm

**Comment by gmt2001** [comment]
MODE, .mods, and IRCv3 tags already change a boolean in the Channel object for that

**Comment by gmt2001** [comment]
Resolved in ac958d8
