### ISSUE TITLE
Songs Requests

### ISSUE THREAD

**Issue by phantomindex** [GloriousEggroll/PhantomBot#9]
I've noticed with some addsong requests they freeze the bot over when these are typed
!addsong lol
!addsong lmao
It's usually one word

The console will freeze up. You won't see any messages from viewers or commands working.

**Comment by GloriousEggroll** [comment]
resolved https://github.com/GloriousEggroll/PhantomBot/commit/b619714bfbf80a2c7d67c0c60cb7bb3b6e778920
